import os
env = Environment(ENV = {'PATH' : os.environ['PATH']})
env.Command("tnt.res", "tnt.rc", "windres $SOURCE --output-format=coff --output=$TARGET")
env.Program('tnt.exe', ["tnt_exe.cpp", "tnt.res"], LIBS=['shlwapi'], LINKFLAGS=['-static', '-s'])
